SouvTech-CMS/frontend

.prettierrc, package.json, public/index.html, src/api/auth.ts, src/api/axiosClient.ts, src/component/App.tsx, src/component/AppLayout.tsx, src/component/Router.tsx, src/component/sidebar/Sidebar.tsx, src/component/sidebar/SidebarListItem.tsx, src/components/Router.tsx, src/configuration.tsx, src/constant/validations.ts, src/context/auth.tsx, src/index.tsx, src/page/Auth.tsx, src/page/NotFound.tsx, src/page/Reports.tsx, src/type/FCC.ts, src/type/auth.ts, src/util/apiBaseUrl.ts, src/util/userToken.ts, yarn.lock
- Добавил роутинг
- Добавил **Chakra UI** для компонентов
- Сделал темплейт для основных страниц
- Добавил сайдбар в темплейт
- Сделал страницу авторизации
- Сделал забавную 404 страницу
- Добавил заготовку под страницу с отчётами
- Сделал, чтобы если юзер не авторизован, его пересылало на страницу авторизации, а после удачной авторизации возвращало обратно
- Сделал, чтобы авторизация происходила через бэкенд (ссылка на API должна быть в `.env`)
- Поменял, чтобы авторизация была не через почту, а через рандомный текстовый логин
=> Chakra UI and auth

src/api/supplier.ts, src/component/sidebar/Sidebar.tsx, src/component/sidebar/SidebarListItem.tsx, src/component/suppliers/NewSupplierCard.tsx, src/component/suppliers/SupplierCard.tsx, src/component/suppliers/SupplierCardMenu.tsx, src/component/suppliers/SupplierDeleteModal.tsx, src/component/suppliers/SupplierModal.tsx, src/configuration.tsx, src/context/auth.tsx, src/context/user.tsx, src/page/Suppliers.tsx, src/service/supplier.ts, src/type/FCC.ts, src/type/supplier.ts
- Добавил страницу поставщиков
- Сделал всё по аналогии с юзерами
=> feat: suppliers page

src/api/purchase.ts, src/api/purchaseGood.ts, src/api/supplier.ts, src/api/supplierManager.ts, src/component/good/GoodRow.tsx, src/component/good/GoodsTable.tsx, src/component/good/NewGoodModal.tsx, src/component/manager/ManagersListModal.tsx, src/component/purchase/NewPurchaseBtn.tsx, src/component/purchase/NewPurchaseModal.tsx, src/component/purchase/PurchaseRow.tsx, src/component/purchase/PurchasesTable.tsx, src/component/suppliers/SupplierModal.tsx, src/component/users/UserCard.tsx, src/component/users/UserModal.tsx, src/constant/purchaseStatus.ts, src/page/Purchases.tsx, src/page/Suppliers.tsx, src/page/Users.tsx, src/service/good.ts, src/service/purchase.ts, src/type/purchase.ts, src/type/purchaseGood.ts
- Сделал страницу закупок
- Добавил создание закупок и товаров в них
=> feat: create purchases with goods

src/api/purchaseDelivery.ts, src/api/purchaseGood.ts, src/component/purchaseDelivery/NewPurchaseDeliveryBtn.tsx, src/component/purchaseDelivery/PurchaseDeliveriesTable.tsx, src/component/purchaseDelivery/PurchaseDeliveryGoodsSelectList.tsx, src/component/purchaseDelivery/PurchaseDeliveryModal.tsx, src/component/purchaseDelivery/SelectedPurchaseGoodCard.tsx, src/constant/tableColumns.ts, src/page/Purchases.tsx, src/service/purchaseDelivery.ts, src/type/purchaseDelivery.ts
- Создание закупки в доставке
- Добавление товаров с последним статусом (`processing`) в закупку в доставке
- Указание дедлайна
=> feat: create purchase delivery

src/api/purchaseDelivery.ts, src/component/document/NewPurchaseDocumentCard.tsx, src/component/document/NewPurchaseDocumentModal.tsx, src/component/document/PurchaseDocumentCard.tsx, src/component/document/PurchaseDocumentDeleteModal.tsx, src/component/document/PurchaseDocumentsModal.tsx, src/component/manager/NewManagerModal.tsx, src/component/purchase/NewPurchaseModal.tsx, src/component/purchase/PurchaseDeleteModal.tsx, src/component/purchaseDelivery/NewPurchaseDeliveryBtn.tsx, src/component/purchaseDelivery/PurchaseDeliveriesTable.tsx, src/component/purchaseDelivery/PurchaseDeliveryDeleteModal.tsx, src/component/purchaseDelivery/PurchaseDeliveryGoodsModal.tsx, src/component/purchaseDelivery/PurchaseDeliveryModal.tsx, src/component/purchaseDelivery/PurchaseDeliveryRow.tsx, src/component/purchaseDelivery/PurchaseDeliveryRowMenu.tsx, src/component/suppliers/NewSupplierCard.tsx, src/component/suppliers/SupplierCard.tsx, src/component/suppliers/SupplierDeleteModal.tsx, src/component/suppliers/SupplierModal.tsx, src/component/users/NewUserCard.tsx, src/component/users/UserCard.tsx, src/page/Purchases.tsx, src/service/purchaseFile.ts, src/type/purchaseDelivery.ts, src/type/purchaseFile.ts, src/util/apiBaseUrl.ts
- Отображение доставок
- Открытие и загрузка документов для доставок
- Просмотр товаров доставки
- Изменение и удаление доставки
=> feat: purchase delivery table

src/api/purchaseDelivery.ts, src/component/PageHeading.tsx, src/component/Router.tsx, src/component/good/PurchaseGoodRow.tsx, src/component/good/PurchaseGoodsStatusUpdateModal.tsx, src/component/manager/NewManagerModal.tsx, src/component/purchase/PurchaseRow.tsx, src/component/purchase/PurchasesTable.tsx, src/component/purchaseDelivery/PurchaseDeliveriesTable.tsx, src/component/purchaseDelivery/PurchaseDeliveryGoodsModal.tsx, src/component/purchaseDelivery/PurchaseDeliveryModal.tsx, src/component/purchaseDelivery/PurchaseDeliveryRow.tsx, src/constant/purchaseStatus.ts, src/constant/tableColumns.ts, src/context/auth.tsx, src/context/purchaseTabs.tsx, src/context/search.tsx, src/context/user.tsx, src/page/Purchases.tsx, src/service/purchaseGood.ts, src/util/goodBadgeColor.ts
- Изменение статуса доставки
- Поиск среди товаров в закупках
- Поиск среди доставок
- Переход на закупки по товару в доставке
=> Purchase delivery fixes

.prettierrc, package.json, src/api/storage.ts, src/api/storageGood.ts, src/component/purchase/PurchaseDeadlineBadge.tsx, src/component/purchase/PurchaseRow.tsx, src/component/purchase/PurchaseSupplierModal.tsx, src/component/purchaseDelivery/GoodToStorageCard.tsx, src/component/purchaseDelivery/PurchaseDeliveryRow.tsx, src/component/purchaseDelivery/PurchaseDeliveryRowMenu.tsx, src/component/purchaseDelivery/PurchaseDeliveryToStorageModal.tsx, src/component/storageGood/ShelfBadge.tsx, src/component/storageGood/StorageGoodRow.tsx, src/hook/useCommentInput.tsx, src/service/storage.ts, src/type/storage.ts, src/type/storageGood.ts, src/util/formatting.ts, yarn.lock
- Перенос товара на склад
- Пофиксил бэйдж в закупках
- Добавил поле поиска при выборе товара со склада
=> Move goods to storage

src/api/axiosClient.ts, src/api/order.ts, src/api/shop.ts, src/component/Pagination.tsx, src/component/document/PurchaseDocumentCard.tsx, src/component/marketplace/MarketplaceAvatar.tsx, src/component/order/OrdersFilters.tsx, src/component/order/OrdersTable.tsx, src/component/order/OrdersTableRow.tsx, src/component/purchaseDelivery/GoodToStorageCard.tsx, src/configuration.tsx, src/constant/tables.ts, src/context/user.tsx, src/hook/useShopFilter.tsx, src/page/Orders.tsx, src/page/Storage.tsx, src/type/apiResponse.ts, src/type/goodInOrder.ts, src/type/order.ts, src/type/selectOption.ts, src/util/formatting.ts, src/util/totalPages.ts, src/util/urls.ts
- Страница заказов
- Фильтр с выбором магазина
- Фильтр, чтобы показывать заказы, где товары с `None`
- Поправил высчитывание кол-ва страниц в пагинации
=> feat: orders page

src/api/order.ts, src/component/Router.tsx, src/component/order/GoodInOrderCard.tsx, src/component/order/OrderProperties.tsx, src/component/order/OrderPropertyRow.tsx, src/component/order/OrdersFilters.tsx, src/component/order/OrdersTable.tsx, src/component/order/OrdersTableRow.tsx, src/component/purchase/PurchasesTable.tsx, src/component/purchaseDelivery/PurchaseDeliveryRow.tsx, src/configuration.tsx, src/page/OrderInfo.tsx, src/type/goodInOrder.ts
- Страница заказа
- Параметры заказа на странице
- Список с карточками товаров и информация о них
=> feat: order info page

src/api/storageGood.ts, src/component/good/GoodModal.tsx, src/component/storageGood/GoodStorageCard.tsx, src/component/storageGood/NewStorageGoodBtn.tsx, src/component/storageGood/StorageGoodModal.tsx, src/component/storageGood/StorageGoodProperties.tsx, src/component/storageGood/StorageGoodPropertyRow.tsx, src/component/storageGood/StorageGoodRow.tsx, src/component/storageGood/StorageGoodRowMenu.tsx, src/configuration.tsx, src/page/Storage.tsx, src/page/StorageGoodDetails.tsx, src/service/storageGood.ts
- Страница товара на складе со списком поставок
- Убрал редактирование SKU на существующих товарах
- Создание товара на складе
=> Storage good page

src/api/detailedReport/detailedReport.ts, src/component/detailedReport/DetailedReportDownloadBtn.tsx, src/component/detailedReport/DetailedReportFilters.tsx, src/component/users/UserCard.tsx, src/hook/useShopFilter.tsx, src/page/DetailedReports.tsx, src/service/detailedReport/detailedReport.ts, src/type/detailedReport/detailedReport.ts
- Добавил кнопку для скачивания детального репорта
- Сделал, чтобы нельзя было выбирать месяц, который ещё не наступил
- Поправил размер шрифта на карточках юзеров
=> feat: btn to download detailed report file

src/api/goods.ts, src/api/order.ts, src/api/storageGood.ts, src/component/Router.tsx, src/component/detailedReport/DetailedReportTable.tsx, src/component/page/Pagination.tsx, src/component/page/RowsPerPageSelect.tsx, src/constant/tables.ts, src/context/pagination.tsx, src/context/purchaseTabs.tsx, src/page/DetailedReports.tsx, src/page/Goods.tsx, src/page/Orders.tsx, src/page/Storage.tsx, src/util/totalPages.ts
- Сделал компонент с выбором количества строк в таблице на одной странице
- Добавил его на страницы: **Goods**, **Orders**, **Storage**
=> feat: select rows per page for tables

src/api/storage.ts, src/component/purchaseDelivery/DeliveryToStorageShopsSelect.tsx, src/component/purchaseDelivery/GoodToStorageCard.tsx, src/component/purchaseDelivery/PurchaseDeliveryToStorageModal.tsx, src/type/storage.ts
- Поправил схему для запроса на перенос товаров из закупки на склад
- Поправил перенос товаров закупки на склад
=> Fix move goods to storage

src/component/document/NewPurchaseDocumentCard.tsx, src/component/document/NewPurchaseDocumentModal.tsx, src/component/document/PurchaseDocumentCard.tsx
- Сделал, чтобы можно было загружать сразу несколько документов на закупках
- Поправил вид карточек документов
=> fix: multiple purchases docs uploading

src/api/storageGood.ts, src/component/order/OrdersFilters.tsx, src/component/storageGood/GoodStorageCard.tsx, src/component/storageGood/StorageGoodProperties.tsx, src/component/storageGood/StorageGoodRow.tsx, src/component/storageGood/StorageGoodsFilters.tsx, src/component/storageGood/StorageGoodsTable.tsx, src/constant/tables.ts, src/page/Orders.tsx, src/page/Storage.tsx, src/page/StorageGoodDetails.tsx, src/type/storage.ts, src/type/storageGood.ts, src/util/formatting.ts
- Поправил схемы для склада и его товаров
- Сделал отображение магазинов на карточках поставок на странице товара
=> Storage goods fixes

src/component/purchase/PurchaseColumnCard.tsx, src/component/purchase/PurchaseGoodsModal.tsx, src/component/purchase/PurchaseGoodsModalCard.tsx, src/component/purchase/PurchaseRowMenu.tsx, src/component/purchase/PurchasesTableStatusColumn.tsx, src/component/purchaseDelivery/DeliveryCardGoodsList.tsx, src/component/purchaseDelivery/DeliveryColumnCard.tsx, src/component/purchaseDelivery/GoodToStorageCard.tsx, src/component/purchaseDelivery/NewPurchaseDeliveryModal.tsx, src/component/purchaseDelivery/PurchaseDeliveriesTableStatusColumn.tsx, src/component/purchaseDelivery/PurchaseDeliveryToStorageModal.tsx, src/component/purchaseGood/DeliveryGoodCard.tsx, src/page/Purchases.tsx, src/type/purchaseDelivery/purchaseDelivery.ts, src/type/purchaseDelivery/purchaseDeliveryGood.ts
- Добавил открытие модалки с товарами закупки
- Добавил поиск по SKU товара среди закупок и посылок
- Добавил фильтр на отображение только тех товаров, где SKU подходит под значение в поиске
=> feat: filter purchases & deliveries by sku in search query

src/api/storage.ts, src/api/storage/storage.ts, src/api/storage/storageGood.ts, src/component/TableTdSkeleton.tsx, src/component/purchaseDelivery/PurchaseDeliveryToStorageModal.tsx, src/component/storageGood/ShelfBadge.tsx, src/component/storageGood/StorageGoodRow.tsx, src/component/storageGood/StorageGoodsTable.tsx, src/page/Storage.tsx, src/page/StorageGoodDetails.tsx, src/service/storage.ts, src/service/storageGood.ts, src/type/storage.ts
- Поправил схему возвращаемую на странице **Storage**
- Добавил подгрузку информации о товаре на каждой строке
=> Storage actual info fixes

package.json, src/api/guide/guide.ts, src/component/Container.tsx, src/component/guide/GuideOpenBtn.tsx, src/component/page/Page.tsx, src/configuration.tsx, src/constant/guides.ts, src/page/DetailedReports.tsx, src/page/Goods.tsx, src/page/Guides.tsx, src/page/OrderInfo.tsx, src/page/Orders.tsx, src/page/ProductionInfo.tsx, src/page/Purchases.tsx, src/page/PurchasesHistory.tsx, src/page/Storage.tsx, src/page/StorageGoodDetails.tsx, src/page/Suppliers.tsx, src/page/Users.tsx, src/type/page/page.ts, src/util/guide.ts, src/util/notion/notion.css, src/util/notion/notion.ts, yarn.lock
- Сделал кнопку для открытия гайда
- Сделал подгрузку гайда с нашего ноушена
=> feat: guides pages

src/component/AppLayout.tsx, src/component/AppRouter.tsx, src/configuration.tsx, src/context/websocket.tsx, src/index.tsx, src/page/Maintenance.tsx, src/util/urls.ts
- Теперь при получении сообщения из вебсокета, будет обновлять нужный кэш
- Добавил страницу "сервис сейчас не доступен"
=> Websocket refetching cache

src/component/purchaseGood/NewPurchaseGoodRow.tsx, src/component/purchaseGood/NewPurchaseGoodRowMenu.tsx, src/component/purchaseGood/PurchaseGoodModal.tsx, src/component/purchaseGood/PurchaseGoodsTable.tsx
- Сделал редактирование товара закупки при создании самой закупки
=> feat: new purchase good editing

src/component/purchaseGood/PurchaseGoodModal.tsx, src/component/purchaseGood/PurchaseGoodsTable.tsx, src/type/purchase/purchaseGood.ts
- Сделал, чтобы при создании товара можно было вводить кол-во и общую сумму за товар
- Item Price считается относительно общей суммы разделённой на кол-во
=> fix: total amount input instead item price

src/component/customTable/CustomTh.tsx, src/component/storageGood/StorageGoodsTable.tsx, src/hook/usePagination.tsx, src/page/Goods.tsx, src/page/Orders.tsx, src/page/ProductionInfo.tsx, src/page/PurchasesHistory.tsx, src/page/Storage.tsx
- Сделал, чтобы при применении фильтрации на колонку, текущая страница сбрасывалась и ставилась на первую
=> fix: reset current page when filter on col

src/component/filter/DatesFilter.tsx, src/component/order/OrdersFilters.tsx, src/component/order/OrdersTable.tsx, src/configuration.tsx, src/constant/tables.ts, src/page/Orders.tsx, src/type/order/order.ts, src/util/formatting.ts
- Сделал поле для ввода периода из 2 дат на **Orders**
- После выбора второй даты ставится `end_date` в `search_filter`
=> feat: orders date filter

src/component/good/GoodsTable.tsx, src/configuration.tsx, src/constant/tables.ts, src/page/Goods.tsx, src/page/Orders.tsx, src/page/Storage.tsx
- Сделал сортировку и фильтрацию на **Goods**
=> feat: goods filtering & sorting

src/component/purchase/NewPurchaseModal.tsx, src/component/purchase/PurchaseColumnCard.tsx, src/component/purchase/PurchaseStatusUpdateModal.tsx, src/component/purchase/PurchaseUpdateModal.tsx, src/type/purchase/purchase.ts
- Сделал ввод депозита на закупках
- Сделал отображение депозита в карточке закупоки
=> feat: purchase deposit

src/api/purchase/purchaseGood.ts, src/api/purchaseDelivery/purchaseDelivery.ts, src/api/supplier/supplierManager.ts, src/component/purchase/PurchaseColumnCard.tsx, src/component/purchase/PurchaseGoodsModalCard.tsx, src/component/purchaseGood/PurchaseGoodDeleteModal.tsx, src/service/purchase/purchaseGood.ts
- Сделал удаление товаров в Закупках
- Сделал, чтобы `total amout` закупки считался, а не брался из базы
=> Purchase goods deleting

src/api/purchase/purchase.ts, src/api/purchase/purchaseService.ts, src/api/supplier/supplier.ts, src/component/purchase/NewPurchaseModal.tsx, src/component/purchase/PurchaseColumnCard.tsx, src/component/purchase/PurchaseRowMenu.tsx, src/component/purchase/PurchaseServicesModal.tsx, src/component/purchase/PurchaseServicesModalCard.tsx, src/component/purchaseDelivery/NewPurchaseDeliveryModal.tsx, src/component/purchaseGood/PurchaseGoodModal.tsx, src/component/purchaseService/NewPurchaseServiceModal.tsx, src/component/purchaseService/NewPurchaseServiceRow.tsx, src/component/purchaseService/NewPurchaseServiceRowMenu.tsx, src/component/purchaseService/PurchaseServiceDeleteModal.tsx, src/component/purchaseService/PurchaseServiceModal.tsx, src/component/purchaseService/PurchaseServicesTable.tsx, src/service/purchase/purchaseService.ts, src/type/purchase/purchase.ts, src/type/purchase/purchaseGood.ts, src/type/purchase/purchaseService.ts, src/type/purchaseDelivery/purchaseDelivery.ts
- Сделал создание, редактирование и удаление доп. затрат на новых Закупках
- Сделал создание, редактирование и удаление доп. затрат на существующих Закупках
=> Purchase services

src/api/tableAccess/tableAccess.ts, src/component/productionInfo/StorageGoodsWithProductionInfoTable.tsx, src/component/role/PermissionsGridItem.tsx, src/component/role/RoleCard.tsx, src/component/role/RoleModal.tsx, src/component/sidebar/Sidebar.tsx, src/component/storageGood/StorageGoodModal.tsx, src/component/tableAccess/ColumnsTagsSelect.tsx, src/component/tableAccess/TableAccessCard.tsx, src/component/tableAccess/TablesAccessModal.tsx, src/configuration.tsx, src/constant/tables.ts, src/service/tableAccess/tableAccess.ts, src/type/selectOption.ts, src/type/tableAccess/tableAccess.ts
- Поправил тело запроса на обновление роли
- Поправил баг, что в модалках на **Storage** не обновлялась инфа о товаре
=> refactor: update role request

src/api/tableAccess/tableAccess.ts, src/api/user.ts, src/component/productionInfo/ProductionInfoTable.tsx, src/component/productionInfo/ProductionInfoTableRow.tsx, src/constant/tables.ts, src/context/user.tsx, src/hook/useUserTableAccess.tsx, src/page/Users.tsx, src/type/tableColumn.ts, src/util/permission.ts
- Сделал получение доступных таблиц с колонками по `ID` ролей юзера
- Сделал отображение только доступных колонок на **Production Info**
=> feat: production info roles columns accessebility

src/component/productionInfo/ProductionInfoTable.tsx, src/component/productionInfo/ProductionInfoTableRow.tsx, src/component/tableAccess/ColumnsTagsSelect.tsx, src/component/tableAccess/NewTableAccessTableSelect.tsx, src/component/tableAccess/TableAccessCard.tsx, src/component/tableAccess/TablesAccessModal.tsx, src/configuration.tsx, src/context/websocket.tsx, src/hook/useUserTableAccess.tsx
- Настроил создание ролей и их прав на таблицах
- Настроил отображение колонок на странице **Production Info**
- Сделал добавление таблицы в список
=> Table access fixes

src/component/Logo.tsx, src/component/detailedReport/DetailedReportTable.tsx, src/component/detailedReport/DetailedReportTableRow.tsx, src/component/good/GoodsTable.tsx, src/component/good/GoodsTableRow.tsx, src/component/order/OrdersFilters.tsx, src/component/order/OrdersTable.tsx, src/component/productionInfo/ProductionInfoTableRow.tsx, src/component/purchase/NewPurchaseModal.tsx, src/component/purchaseGood/NewPurchaseGoodRow.tsx, src/component/purchaseGood/PurchaseGoodsTable.tsx, src/component/purchaseService/NewPurchaseServiceRow.tsx, src/component/purchaseService/PurchaseServicesTable.tsx, src/component/sidebar/Sidebar.tsx, src/component/sidebar/SidebarCollapseBtn.tsx, src/component/sidebar/SidebarListItem.tsx, src/component/storageGood/StorageGoodRow.tsx, src/component/storageGood/StorageGoodsTable.tsx
- Запихнул все таблицы в контейнер, чтобы при сужении экрана они не выходили за границу и их можно было листать
- Сделал сайдбар скрывающимся
=> Wrap tables in container

src/api/storage/storage.ts, src/component/purchase/PurchaseGoodsModalCard.tsx, src/component/storage/StorageModal.tsx, src/component/storage/StorageShopSelect.tsx, src/type/storage/storage.ts
- Добавил селект с выбором магазинов при создании и редактировании **Storage Records**
=> fix: purchases goods cards rounding

src/api/purchase/purchasesHistory.ts, src/component/document/DeliveryDocumentsModal.tsx, src/component/document/PurchaseDocumentsModal.tsx, src/component/purchase/PurchaseGoodsModal.tsx, src/component/purchase/PurchaseGoodsModalCard.tsx, src/component/purchaseDeliveryService/DeliveryServicesModal.tsx, src/component/purchaseHistory/DeliveryHistoryRowMenu.tsx, src/component/purchaseHistory/DeliveryHistoryTableRow.tsx, src/component/purchaseHistory/PurchaseHistoryRowMenu.tsx, src/component/purchaseHistory/PurchaseHistoryTable.tsx, src/component/purchaseHistory/PurchaseHistoryTableRow.tsx, src/component/purchaseService/PurchaseServicesModal.tsx, src/component/purchaseService/PurchaseServicesModalCard.tsx, src/configuration.tsx, src/constant/tables.ts, src/page/PurchasesHistory.tsx, src/type/modalProps.ts, src/type/purchase/purchaseHistory.ts
- добавил отображение сервисы закупок в историю закупок
- добавил фильтрацию и сортировку на историю закупок
- добавил ограничения на редактирование для тех, кто не админ
=> fix: history filters & services history & disable editing

src/api/authorizedDevice/authorizedDevice.ts, src/api/axiosClient.ts, src/component/authorizedDevice/DeviceCard.tsx, src/component/authorizedDevice/DeviceCardMenu.tsx, src/component/authorizedDevice/DeviceDeleteModal.tsx, src/component/authorizedDevice/DeviceModal.tsx, src/component/authorizedDevice/NewDeviceCard.tsx, src/component/engraver/EngraverModal.tsx, src/component/sidebar/Sidebar.tsx, src/configuration.tsx, src/hook/useAuthorizedDevice.tsx, src/page/AuthorizedDevices.tsx, src/service/authorizedDevice/authorizedDevice.ts, src/type/authorizedDevice/authorizedDevice.ts, src/util/authorizedDevice.ts
- Страница авторизованных устройств
- Авторизация текущего устройства
- Сохранение токена устройства в локальный сторадж
- Проверка, что текущее устройство авторизовано
=> Authorized devices

src/api/analytics/sales.ts, src/api/client/country.ts, src/api/client/state.ts, src/component/chart/ChartCard.tsx, src/component/chart/ChartSection.tsx, src/component/chart/FiltersPopover.tsx, src/component/chart/MonthTotalCharts.tsx, src/component/chart/OrdersPerDayChart.tsx, src/component/chart/SalesCitiesChart.tsx, src/component/chart/SalesStatesChart.tsx, src/component/filter/DatesFilter.tsx, src/component/filter/ShopFilter.tsx, src/component/select/CountrySelect.tsx, src/component/select/StateSelect.tsx, src/configuration.tsx, src/page/Dashboard.tsx, src/type/analytics/city.ts, src/type/analytics/sales.ts, src/type/client/country.ts, src/type/client/state.ts, src/util/colors.ts, src/util/dates.ts
- Топ 10 штатов по продажам
- Топ 10 городов в штате по продажам
=> feat: sales states & cities analytics

src/api/client/client.ts, src/component/badge/ShopBadge.tsx, src/component/client/ClientProperties.tsx, src/component/client/ClientRow.tsx, src/component/client/ClientsTable.tsx, src/component/marketplace/MarketplaceBadge.tsx, src/component/order/MarketplaceOrderLink.tsx, src/component/order/OrderCard.tsx, src/component/order/OrderProperties.tsx, src/component/order/OrdersTableRow.tsx, src/component/property/PropertiesList.tsx, src/component/property/PropertyRow.tsx, src/component/select/StateSelect.tsx, src/configuration.tsx, src/constant/tables.ts, src/page/ClientDetails.tsx, src/page/Clients.tsx, src/page/Dashboard.tsx, src/page/StorageGoodDetails.tsx, src/type/client/client.ts, src/type/client/marketplace.ts, src/type/order/order.ts, src/type/property.ts
- **Clients Table Page**
- **Client Details Page** with its Orders + redirect to **Order Details Page**
=> feat: clients table page & client details page & refactor some components
